--=======================================================================--                   
				   -- DataWarehouseAnalytics Project --
--=======================================================================--
                     -- ( DIMENSIONS EXPLORATION ) --
                        USE DataWarehouseAnalytics
-- Activity 1 - Dimensions Exploration
-- Q1. Retrieve a list of unique countries from which customers originate.
Select Distinct(country) from Gold.dim_Customers;

-- Q2. Retrieve a list of unique categories, subcategories, and products
Select Category , Subcategory ,product_name from Gold.dim_products
Group by Category , Subcategory ,product_name;

--=======================================================================--
                        -- ( DATE EXPLORATION ) --
-- Activity 2 - Date Range Exploration
-- Q1. Determine the first and last order date and the total duration in months
Select 
	Min(Order_date)as First_Order,
	Max(Order_date)As Last_Order,
	DATEDIFF(month,Min(Order_date),Max(Order_date)) AS Total_Duration
	From Gold.fact_sales
-- Q2. Find the youngest and oldest customer based on birthdate
-- youngest customer--
Select * 
From Gold.dim_customers
Where birthdate =( select Min(Birthdate) from Gold.dim_customers )
-- oldest customer--
Select *
From Gold.dim_customers
Where birthdate =(select MAX(Birthdate) from Gold.dim_customers )
--=======================================================================--
                     -- ( MEASURES EXPLORATION ) --
-- Activity 3 - Measures Exploration (Key Metrics)
-- Q1. Find the Total Sales
Select Sum(sales_amount) As Total_Sales
From Gold.fact_sales

-- Q2. Find how many items are sold
Select Sum(quantity) as Item_solid From Gold.fact_sales

-- Q3. Find the average selling price
Select AVG(price) As AVG_Price From Gold.fact_sales

-- Q4. Find the Total number of Orders
Select Count(order_number) as No_Orders From Gold.fact_sales

-- Q5. Find the total number of products
Select Count(Distinct(Product_name)) As NO_Product From Gold.dim_products

-- Q6. Find the total number of customers
Select Count(Distinct(customer_id)) As NO_Customer From Gold.dim_customers

-- Q7. Find the total number of customers that has placed an order
Select Count(Distinct(customer_key)) As No_Customer_Placed_Order From Gold.fact_sales	

-- Q8. Generate a Report that shows all key metrics of the business
Select
Sum(sales_amount)As Total_Sales,
Sum(quantity) as Item_solid,
AVG(price)As AVG_Price,
Count(order_number)as No_Orders,
Count(Distinct(s.customer_key))As No_Customer_Placed_Order,
Count(Distinct(Product_name))As NO_Product,
Count(Distinct(customer_id))As NO_Customer
 From (Gold.dim_customers C
	Join Gold.fact_sales S on C.customer_key = S.customer_key 
	Join Gold.dim_products P on s.product_key = p.product_key
	)

--=======================================================================--
                           -- ( MAGNITUDE ) --
-- Activity 4 - Magnitude Analysis
-- Q1. Find total customers by countries.
Select country ,Count(Distinct(Customer_Key)) AS Total_Cutomer  From Gold.dim_customers
Group by country 

-- Q2. Find total customers by gender
Select gender ,Count(Distinct(Customer_Key)) AS Total_Cutomer  From Gold.dim_customers
Group by gender

-- Q3. Find total products by category
Select category ,Count(Distinct(product_key)) AS Total_product  From Gold.dim_products
Group by category

-- Q4. What is the average costs in each category?
Select category ,Avg(Cost) AS Avg_Cost  From Gold.dim_products
Group by category

-- Q5. What is the total revenue generated for each category?
Select category ,Sum(sales_amount) AS Total_Revenue 
From Gold.fact_sales S
Join Gold.dim_products P 
On S.product_key = P.product_key
Group by category

-- Q6. What is the total revenue generated by each customer?
Select customer_id,  Sum(sales_amount) AS Total_Revenue 
From Gold.fact_sales S
Join Gold.dim_customers C 
On S.customer_key = C.customer_key
Group by customer_id

-- Q7. What is the distribution of sold items across countries?
Select Country,Sum(Quantity) As Item_Sold
From Gold.dim_customers C
Join Gold.fact_sales S
ON C.customer_key = S.customer_key
Where country <> 'n/a'
Group by country

--=======================================================================--
                   -- ( CHANGE OVER TIME TRENDS ) --
-- Activity 5 - Analyze sales performance over time- Via Date Functions
-- Q1. Find the yearly & Monthly Sales with total customer count.
-- Years -- 
Select 
Year(Order_Date) AS Order_Year,
Month(Order_Date) AS Order_Months ,
Sum(Sales_Amount) As Total_Sales,
Count(Distinct customer_key) As Total_customer
From Gold.fact_sales
Where order_date is not null
Group by Year(order_date),Month(Order_Date)
Order by Year(order_date),Month(Order_Date)

-- Q2. Find the yearly & Monthly Sales with total customer count. (Using DATETRUNC)
Select 
Datetrunc(Year,Order_Date) AS Order_Year ,
Sum(Sales_Amount) As Total_Sales,
Count(Distinct(customer_key)) As Total_customer
From Gold.fact_sales
Where order_date is not null
Group by Datetrunc(Year,Order_Date)
Order by Datetrunc(Year,Order_Date)

-- Q3. Find the yearly & Monthly Sales with total customer count. FORMAT()
Select 
Format(Order_Date,'yyyy-MMMM') AS Order_Year ,
Sum(Sales_Amount) As Total_Sales,
Count(Distinct(customer_key)) As Total_customer
From Gold.fact_sales
Where order_date is not null
Group by Format(Order_Date,'yyyy-MMMM')
Order by Format(Order_Date,'yyyy-MMMM')

--=======================================================================--
                             -- T.H.A.K.S  Y.O.U --
--=======================================================================--
